[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  # Disable secrets scanning for expected public environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

# API function redirects (handle all /api/* routes with the api function)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA routing redirects (for everything else)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Don't redirect API calls
  conditions = {Role = [""], "Country" = [""]}
  force = false