[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Disable secrets scanning for expected public environment variables
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

# Optional: Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200